server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址,集群版
          predicates:
          - Path=/payment/get/**  #断言，路径相匹配的进行路由
        - id: payment_routh2  #payment_route
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址,集群版
          predicates:
            - Path=/payment/lb/**
           # - After=2020-04-27T09:31:41.560+08:00[Asia/Shanghai] #表明在此时间后才可以访问到
         #   - Cookie=username,zzyy # Cookie 匹配 cookie名称，正则表达式
           # - Header=X-Request-Id, \d+ #带请求头X-Request_Id访问，且值为整数

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka