server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group #自定义事务组名称需要与seata-server中对应
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: root

feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info


mybatis:
  mapper-locations: classpath:mapper/*.xml

# 解决feign调用超时 feign.RetryableException: Read timed out executing POST
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
