server:
  port: 8004

spring:
  application:
    name: cloud-payment-service #入驻进eureka服务的注册名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

    #注册到zookeeper
  cloud:
    zookeeper:
      connect-string: 192.168.10.11:2181

mybatis:
  type-aliases-package: com.atguigu.springcloud.entity #所有entity别名类所在包
  mapper-locations: classpath:mapper/*.xml
